--- # Install and configure Mysql 
- hosts: all
  become: yes
  become_method: sudo
  vars:
    mysql_root_pass: test_Pass #We can provide using askpass or valut

  tasks:
    - name: Install the MySQL packages
      apt: name={{ item }} state=installed update_cache=yes
      with_items:
         - mysql-server-5.7
         - mysql-client-5.7
         - python-mysqldb
         - libmysqlclient-dev

    - name: Update MySQL root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
      with_items:
         - "{{ ansible_hostname }}"
         - 127.0.0.1
         - ::1
         - localhost

    - name: Copy the root credentials as .my.cnf file
      template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

    - name: Webapp user creation in the database
      mysql_user: name=webapp host={{ item }} password={{ mysql_root_pass }} state=present
      with_items:
        - localhost
        - "{{ ansible_hostname }}"

    - name: Restart MySQL
      service: name=mysql state=restarted
      
    - name: update the key sensu
      shell: wget -q https://sensu.global.ssl.fastly.net/apt/pubkey.gpg -O- | sudo apt-key add -
    
    - name: configure the sensu repo
#  apt_repository:
#   repo: deb https://sensu.global.ssl.fastly.net/apt trusty main
#   state: present
      shell: echo "deb https://sensu.global.ssl.fastly.net/apt trusty main" > /etc/apt/sources.list.d/sensu.list

    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes

    - name: Install sensu-client
      apt: name= sensu state=installed update_cache=yes

    - name: copy the config json files
      template:
        src: {{ item }}
        dest: /etc/sensu/conf.d/{{ item }}
        remote_src: yes   
       with_items:
         - mysql_check.json
         - client.json
    - name: copy the rabbitmq config
      template:
        src: config.json
        dest: /etc/sensu/config.json

    - name: Install the checks
      shell: /usr/bin/sensu-install -p disk-checks ; /usr/bin/sensu-install -p memory-checks ; /usr/bin/sensu-install -p load-checks

    - name: start the services
      service: name=sensu-client state=started

