--- # Install and configure Mysql 
- hosts: all
  become: yes
  become_method: sudo
  vars:
    mysql_root_pass: test_Pass #We can provide using askpass or valut

  tasks:
    - name: Install the MySQL packages
      apt: name={{ item }} state=installed update_cache=yes
      with_items:
         - mysql-server-5.7
         - mysql-client-5.7
         - python-mysqldb
         - libmysqlclient-dev

    - name: Update MySQL root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
      with_items:
         - "{{ ansible_hostname }}"
         - 127.0.0.1
         - ::1
         - localhost

    - name: Copy the root credentials as .my.cnf file
      template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

    - name: Webapp user creation in the database
      mysql_user: name=webapp host={{ item }} password={{ mysql_root_pass }} state=present
      with_items:
        - localhost
        - "{{ ansible_hostname }}"

    - name: Restart MySQL
      service: name=mysql state=restarted
