# Require the AWS provider plugin
require 'vagrant-aws'

# Create and configure the AWS instance(s)
Vagrant.configure('2') do |config|

  # Use dummy AWS box
  config.vm.box = 'aws-dummy'

  # Specify AWS provider configuration
  config.vm.provider :aws do |aws, override|
    # Read AWS authentication information from environment variables
    aws.access_key_id = ENV['access_key_id']
    aws.secret_access_key = ENV['secret_access_key']

    # Specify SSH keypair to use
    aws.keypair_name = 'one'

    # Specify region, AMI ID, and security group(s)
    aws.region = 'us-west-1'
    aws.ami = 'ami-45ead225'
    aws.instance_type = "t2.micro"
    aws.security_groups = ['vagrant']

    # Specify username and private key path
    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = '~/.ssh/one.pem'
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "webapp.yml"
  end
end
