---

- hosts: all
  become: yes
  become_method: sudo
  
  environment: 
    JAYCONFIG: /opt/blueprint/go/src/github.com/blue-jay/blueprint/env.json
    

  tasks:
   - name: Download the Go tar 
     get_url:
       url: https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz
       dest: /usr/local/src

   - name: Extract the Go tar 
     unarchive:
       src: /usr/local/src/go1.9.2.linux-amd64.tar.gz
       dest: /usr/local
       copy: no

   - name: create a directory 
     file:
      path: /opt/blueprint
      state: directory
      mode: 0755

#   - name: Environment variable
#    shell: echo "export PATH=$PATH:/usr/local/go/bin" >> /etc/profile ; echo "export GOROOT="/usr/local/go"" >> /etc/profile ; echo "export GOPATH="/opt/blueprint/go"" >> /etc/profile
#     run_once: true

#   - name: Source the profile
#     raw: source /etc/profile

   - name: Download blueprint code
     shell: /usr/local/go/bin/go get github.com/blue-jay/blueprint

   - name: Download jay code
     shell: /usr/local/go/bin/go get github.com/blue-jay/jay

   - name: Remove old go webapp
     command: rm -rf /opt/blueprint/go
   
   - name: copying to blueprint
     command: mv /root/go /opt/blueprint    

   - name: configure envjson
     copy: 
      src: /opt/blueprint/go/src/github.com/blue-jay/blueprint/env.json.example
      dest: /opt/blueprint/go/src/github.com/blue-jay/blueprint/env.json
      remote_src: yes

   - name:  Jinja template for envjson
     template:
      src: env.json.j2
      dest: /opt/blueprint/go/src/github.com/blue-jay/blueprint/env.json
  
#   - name: source the profile 
#     shell: source /etc/profile executable=/bin/bash

   - name: Run the blurprint
     shell: export PATH=$PATH:/usr/local/go/bin; export GOROOT="/usr/local/go" ; export GOPATH="/opt/blueprint/go"; nohup /usr/local/go/bin/go run /opt/blueprint/go/src/github.com/blue-jay/blueprint/blueprint.go >/dev/null 2>&1 &
     args: 
      chdir: /opt/blueprint/go/src/github.com/blue-jay/blueprint 
   
   - name: Run the application
     shell: export JAYCONFIG=/opt/blueprint/go/src/github.com/blue-jay/blueprint/env.json; /opt/blueprint/go/bin/jay migrate:mysql all
     
   - name: update the key sensu
     shell: wget -q https://sensu.global.ssl.fastly.net/apt/pubkey.gpg -O- | sudo apt-key add -
     
   - name: configure the sensu repo
#  apt_repository:
#   repo: deb https://sensu.global.ssl.fastly.net/apt trusty main
#   state: present
     shell: echo "deb https://sensu.global.ssl.fastly.net/apt trusty main" > /etc/apt/sources.list.d/sensu.list
     
   - name: Run the equivalent of "apt-get update"
     apt:
       update_cache: yes

   - name: Install sensu-client
     apt: name= sensu state=installed update_cache=yes

   - name: copy the config json files
     template:
       src: {{ item }}
       dest: /etc/sensu/conf.d/{{ item }}
       remote_src: yes
     with_items:
       - web_check.json
       - client.json

   - name: copy the rabbitmq config
     template:
      src: config.json
      dest: /etc/sensu/config.json

   - name: Install the checks
     shell: /usr/bin/sensu-install -p disk-checks ; /usr/bin/sensu-install -p memory-checks ; /usr/bin/sensu-install -p load-checks

   - name: start the services
     service: name=sensu-client state=started
                                               
